on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Install nodejs
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
    - name: Build project
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm install
        npm run build
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
